### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by r3valkyrie** [r3valkyrie/phantomeye-darkrpmodification#7]
HP:
- [x] Remove FA:S weapons
- [x] Install M9K weapons
- [ ] Complete gun dealer shipments
- [ ] Disable weapon-drop on death
- [ ] Add black market dealer job
- [ ] Rewrite loading screen with garbo php

LP:
- [ ] Disable money drop on death?
